### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by bartoszlenar** [bartoszlenar/Validot#14]
## Feature description

* Russian translation for the default Validot's message set.
* Placeholders support where applicable.
* Fluent api extension method to `ValidatorSettings` so it can be nicely used from `Validator.Factory.Create`.

## Feature in action

``` csharp
var validator = Validator.Factory.Create(
    specification,
    s => s.WithRussianTranslation()
);

validator.Settings.Translations["Russian"] // this is the full translation dictionary

validator.Validate(model).ToString(translationName: "Russian") // gets result error output in Russian
```

## Feature implementation walkthrough
* There is a similar feature request (#11) regarding the Spanish language. In the [details of that issue](https://github.com/bartoszlenar/Validot/issues/11) I described the full, end-to-end walkthrough how to implement a translation and all the instructions can be applied here as well.

**Comment by Nanodesy** [comment]
Hi @bartoszlenar! I can help with translation into Russian 🐘

**Comment by bartoszlenar** [comment]
Hi @Nanodesy !

Yes, that would be wonderful. Thank you so much for your willingness to help!

As mentioned in the issue description, the step-by-step guide is contained here: https://github.com/bartoszlenar/Validot/issues/11

You can also refer to the PR regarding Spanish translation: https://github.com/bartoszlenar/Validot/pull/18

If you need any further help of have any questions regarding this - don't hesitate to ask, I'll do my best.

**Comment by bartoszlenar** [comment]
Already merged: https://github.com/bartoszlenar/Validot/pull/19
